"""
cuntz_fock.py — Truncated Cuntz algebra and Boltzmann Fock space.

The master field lives in a Fock space generated by creation operators a†_i
satisfying the Cuntz algebra:
    a_i a†_j = δ_ij       (NO additional relation for a†_j a_i)
    Σ_i a†_i a_i = 1 - |Ω><Ω|

States are labelled by words w = i_1 i_2 ... i_k in the alphabet {1,...,n_matrices}.
The Fock space is truncated at word length L.
"""

from itertools import product as cart_product

import numpy as np


class Word:
    """A word in n letters, representing a Fock space basis state."""

    __slots__ = ["letters"]

    def __init__(self, letters: tuple[int, ...] = ()):
        self.letters = tuple(letters)

    @property
    def length(self):
        return len(self.letters)

    def __repr__(self):
        if not self.letters:
            return "|Ω>"
        return "|" + "".join(str(l) for l in self.letters) + ">"

    def __hash__(self):
        return hash(self.letters)

    def __eq__(self, other):
        return self.letters == other.letters

    def prepend(self, i: int) -> "Word":
        """a†_i |w> = |i w>"""
        return Word((i,) + self.letters)

    def remove_first(self) -> tuple[int, "Word"]:
        """a_i |i w> = |w>,  a_i |j w> = 0 if i≠j"""
        if not self.letters:
            return None, None
        return self.letters[0], Word(self.letters[1:])

    def cyclic_canonical(self) -> "Word":
        """Canonical representative under cyclic permutation (for trace)."""
        if not self.letters:
            return self
        rotations = [self.letters[i:] + self.letters[:i] for i in range(len(self.letters))]
        return Word(min(rotations))


def enumerate_words(n_matrices: int, max_length: int) -> list[Word]:
    """Enumerate all words up to length max_length in n_matrices letters."""
    words = [Word()]  # vacuum
    for length in range(1, max_length + 1):
        for combo in cart_product(range(n_matrices), repeat=length):
            words.append(Word(combo))
    return words


def enumerate_trace_words(n_matrices: int, max_length: int) -> list[Word]:
    """Enumerate distinct cyclic equivalence classes (for trace invariants).

    tr[M_{i1} ... M_{ik}] is invariant under cyclic permutation of indices.
    We pick one canonical representative per class.
    """
    seen = set()
    trace_words = []
    for length in range(1, max_length + 1):
        for combo in cart_product(range(n_matrices), repeat=length):
            w = Word(combo)
            canon = w.cyclic_canonical()
            if canon not in seen:
                seen.add(canon)
                trace_words.append(canon)
    return trace_words


class CuntzFockSpace:
    """Truncated Boltzmann Fock space with Cuntz algebra operators.

    Basis: |Ω>, |i>, |ij>, |ijk>, ... for i,j,k ∈ {0,...,n-1}, up to length L.
    Dimension: 1 + n + n² + ... + n^L = (n^{L+1} - 1)/(n - 1)  for n>1.

    Operators a_i, a†_i act as:
        a†_i |w> = |iw>          (prepend letter i)
        a_i  |Ω> = 0
        a_i  |jw> = δ_{ij} |w>  (remove first letter if it matches)

    The master field is then:
        M̂ = a + Σ_n M_n (a†)^n     (one matrix, Voiculescu form)
    or in Hermitian form:
        M̂ = λ(a + a†) = λ(x̂)       (function of position operator)
    """

    def __init__(self, n_matrices: int, max_length: int):
        self.n = n_matrices
        self.L = max_length
        self.words = enumerate_words(n_matrices, max_length)
        self.dim = len(self.words)
        self.word_to_idx = {w: i for i, w in enumerate(self.words)}

        # Precompute annihilation operator matrices
        self._a_matrices = {}
        self._adag_matrices = {}
        for i in range(n_matrices):
            self._a_matrices[i] = self._build_annihilation(i)
            self._adag_matrices[i] = self._a_matrices[i].T  # a†_i = (a_i)^T in this basis

    def _build_annihilation(self, i: int) -> np.ndarray:
        """Build matrix representation of a_i in the truncated Fock space."""
        mat = np.zeros((self.dim, self.dim))
        for w_idx, w in enumerate(self.words):
            first, remainder = w.remove_first()
            if first is not None and first == i:
                if remainder in self.word_to_idx:
                    rem_idx = self.word_to_idx[remainder]
                    mat[rem_idx, w_idx] = 1.0
        return mat

    def a(self, i: int) -> np.ndarray:
        """Annihilation operator a_i."""
        return self._a_matrices[i]

    def adag(self, i: int) -> np.ndarray:
        """Creation operator a†_i."""
        return self._adag_matrices[i]

    def x(self, i: int) -> np.ndarray:
        """Position operator x̂_i = a_i + a†_i (Hermitian)."""
        return self.a(i) + self.adag(i)

    def p(self, i: int) -> np.ndarray:
        """Momentum operator p̂_i = (a_i - a†_i)/2 (anti-Hermitian)."""
        return 0.5 * (self.a(i) - self.adag(i))

    def vacuum_projector(self) -> np.ndarray:
        """P_Ω = |Ω><Ω|."""
        P = np.zeros((self.dim, self.dim))
        P[0, 0] = 1.0
        return P

    def vacuum_state(self) -> np.ndarray:
        """Column vector |Ω>."""
        v = np.zeros(self.dim)
        v[0] = 1.0
        return v

    def vev(self, operator: np.ndarray) -> float:
        """Vacuum expectation value <Ω|O|Ω>."""
        return operator[0, 0]

    def verify_cuntz_relations(self, tol: float = 1e-12) -> bool:
        """Verify a_i a†_j = δ_{ij} (up to truncation boundary effects)."""
        ok = True
        for i in range(self.n):
            for j in range(self.n):
                prod = self.a(i) @ self.adag(j)
                target = float(i == j) * np.eye(self.dim)
                # Only check the interior (not the boundary where truncation matters)
                interior_dim = sum(1 for w in self.words if w.length < self.L)
                diff = np.max(
                    np.abs(
                        prod[:interior_dim, :interior_dim] - target[:interior_dim, :interior_dim]
                    )
                )
                if diff > tol:
                    ok = False
                    print(
                        f"Cuntz relation a_{i} a†_{j} = δ_{{{i}{j}}} violated: max err = {diff:.2e}"
                    )

        # Verify completeness: Σ_i a†_i a_i = 1 - P_Ω
        lhs = sum(self.adag(i) @ self.a(i) for i in range(self.n))
        rhs = np.eye(self.dim) - self.vacuum_projector()
        interior_dim = sum(1 for w in self.words if w.length < self.L)
        diff = np.max(np.abs(lhs[:interior_dim, :interior_dim] - rhs[:interior_dim, :interior_dim]))
        if diff > tol:
            ok = False
            print(f"Completeness violated: max err = {diff:.2e}")

        if ok:
            print(f"✓ Cuntz algebra verified (n={self.n}, L={self.L}, dim={self.dim})")
        return ok

    def build_master_field_voiculescu(self, coeffs: np.ndarray, matrix_idx: int = 0) -> np.ndarray:
        """Build master field in Voiculescu form:
        M̂ = a + Σ_{n=0}^{L-1} M_n (a†)^n

        Args:
            coeffs: array of M_0, M_1, ..., M_{L-1}
            matrix_idx: which matrix variable (for multi-matrix models)
        """
        ai = self.a(matrix_idx)
        ai_dag = self.adag(matrix_idx)

        M_hat = ai.copy()
        adag_power = np.eye(self.dim)  # (a†)^0 = I
        for _n, Mn in enumerate(coeffs):
            M_hat += Mn * adag_power
            adag_power = adag_power @ ai_dag
        return M_hat

    def build_master_field_hermitian(
        self, func_coeffs: np.ndarray, matrix_idx: int = 0
    ) -> np.ndarray:
        """Build master field in Hermitian form:
        M̂ = λ(x̂_i) = Σ_k c_k x̂_i^k

        where x̂ = a + a† and λ(x) maps the Gaussian eigenvalue density
        to the target density.

        Args:
            func_coeffs: polynomial coefficients c_0, c_1, ..., c_K for λ(x)
        """
        xi = self.x(matrix_idx)
        M_hat = np.zeros((self.dim, self.dim))
        xi_power = np.eye(self.dim)
        for ck in func_coeffs:
            M_hat += ck * xi_power
            xi_power = xi_power @ xi
        return M_hat

    def compute_moments(self, M_hat: np.ndarray, max_power: int = None) -> np.ndarray:
        """Compute tr[M̂^p] = <Ω|M̂^p|Ω> for p = 0, 1, ..., max_power."""
        if max_power is None:
            max_power = self.L
        moments = np.zeros(max_power + 1)
        M_power = np.eye(self.dim)
        for p in range(max_power + 1):
            moments[p] = self.vev(M_power)
            M_power = M_power @ M_hat
        return moments

    def compute_mixed_moments(self, operators: list[np.ndarray], word: tuple[int, ...]) -> float:
        """Compute tr[M_{i1} M_{i2} ... M_{ik}] = <Ω|M̂_{i1} ... M̂_{ik}|Ω>.

        Args:
            operators: list of master field operators M̂_0, M̂_1, ...
            word: tuple of indices (i1, i2, ..., ik)
        """
        product = np.eye(self.dim)
        for idx in word:
            product = product @ operators[idx]
        return self.vev(product)

    def build_unitary_gaussian(self, alpha: float, matrix_idx: int = 0) -> np.ndarray:
        """Build Û_μ = exp(iα(â_μ + â_μ†)) via matrix exponential.

        This is the axial-gauge Gaussian master field for 2D lattice Yang-Mills.
        Unitary exactly on the infinite Fock space, approximately on truncation.
        """
        from scipy.linalg import expm

        M_hat = self.x(matrix_idx)  # â + â†
        return expm(1j * alpha * M_hat)

    def wilson_loop_vev(
        self,
        operators: dict[int, np.ndarray],
        word: tuple[int, ...],
    ) -> complex:
        """Compute W[C] = <Ω| Û_{μ_1} Û_{μ_2} ... Û_{μ_k} |Ω> for a lattice loop.

        Args:
            operators: dict mapping direction μ (1..D) to unitary operator Û_μ.
                Negative indices are handled by taking conjugate transpose.
            word: tuple of signed step indices. μ > 0 → Û_μ; μ < 0 → Û_{|μ|}†.
        """
        if not word:
            return 1.0 + 0j

        product = np.eye(self.dim, dtype=complex)
        for step in word:
            if step > 0:
                U = operators[step]
            else:
                U = operators[-step].conj().T
            product = product @ U
        return complex(self.vev(product))

    def check_unitarity(self, U: np.ndarray, tol: float = 1e-6) -> tuple[bool, float]:
        """Check if U is unitary on the truncated Fock space.

        Returns (is_unitary, ||UU† - I||_F).
        The truncation introduces a boundary term; the error decreases as L grows.
        """
        UU = U @ U.conj().T
        eye = np.eye(self.dim, dtype=UU.dtype)
        err = float(np.linalg.norm(UU - eye, ord="fro"))
        return err < tol, err


# ═══════════════════════════════════════════════════════════════
# Convenience: build the number operator (complicated in Cuntz!)
# ═══════════════════════════════════════════════════════════════


def build_number_operator(fock: CuntzFockSpace, matrix_idx: int = 0) -> np.ndarray:
    """N̂ = Σ_{k=1}^L (a†)^k a^k

    In the Cuntz algebra this is NOT simply a†a.
    It counts the 'position' of a particle in the word.
    """
    a = fock.a(matrix_idx)
    adag = fock.adag(matrix_idx)
    N_hat = np.zeros((fock.dim, fock.dim))
    adag_k = adag.copy()
    a_k = a.copy()
    for _k in range(1, fock.L + 1):
        N_hat += adag_k @ a_k
        adag_k = adag_k @ adag
        a_k = a_k @ a
    return N_hat


if __name__ == "__main__":
    # Quick validation
    print("=" * 60)
    print("Cuntz–Fock space validation")
    print("=" * 60)

    # Single matrix, L=6
    fock = CuntzFockSpace(n_matrices=1, max_length=6)
    fock.verify_cuntz_relations()

    # Gaussian master field: M̂ = a + a† = x̂
    # Moments should be Catalan numbers: tr[M^{2k}] = C_k
    M_gauss = fock.x(0)
    moments = fock.compute_moments(M_gauss, max_power=10)
    catalan = [1, 1, 2, 5, 14, 42]
    print("\nGaussian master field M̂ = â + â†:")
    print(f"  tr[M^0] = {moments[0]:.6f}  (exact: 1)")
    print(f"  tr[M^1] = {moments[1]:.6f}  (exact: 0)")
    print(f"  tr[M^2] = {moments[2]:.6f}  (exact: 1 = C_1)")
    print(f"  tr[M^4] = {moments[4]:.6f}  (exact: 2 = C_2)")
    print(f"  tr[M^6] = {moments[6]:.6f}  (exact: 5 = C_3)")
    print(f"  tr[M^8] = {moments[8]:.6f}  (exact: 14 = C_4)")
    print(f"  tr[M^10]= {moments[10]:.6f} (exact: 42 = C_5)")

    # Two matrices
    fock2 = CuntzFockSpace(n_matrices=2, max_length=4)
    fock2.verify_cuntz_relations()
    print(f"\nTwo-matrix Fock space: dim = {fock2.dim}")

    # Free product test: tr[M1 M2 M1 M2] for independent Gaussians
    M1 = fock2.x(0)
    M2 = fock2.x(1)
    mixed = fock2.vev(M1 @ M2 @ M1 @ M2)
    # For free semicircular variables with unit variance:
    # tr[M1 M2 M1 M2] = tr[M1^2]*tr[M2^2] + (tr[M1])^2*(tr[M2^2]) - ... = 1
    print(f"\nFree product: tr[M1 M2 M1 M2] = {mixed:.6f}")
    print(f"  (Expected for free semicirculars: {1.0})")
